name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'projects/mckit/core/package.json'
      - 'projects/mckit/auth/package.json'
      - 'projects/mckit/cron/package.json'
      - 'projects/mckit/filter/package.json'
      - 'projects/mckit/layout/package.json'
      - 'projects/mckit/layout-core/package.json'
      - 'projects/mckit/layout-sakai/package.json'
      - 'projects/mckit/layout-fuse/package.json'
      - 'projects/mckit/loader/package.json'
      - 'projects/mckit/table/package.json'
      - 'projects/mckit/odata/package.json'
      - 'projects/mckit/form/package.json'
      - 'projects/mckit/tenant/package.json'
      - 'projects/mckit/chat/package.json'
      - 'projects/mckit/socket/package.json'
      - 'projects/mckit/monaco-field/package.json'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.filter.outputs.core }}
      auth: ${{ steps.filter.outputs.auth }}
      cron: ${{ steps.filter.outputs.cron }}
      filter: ${{ steps.filter.outputs.filter }}
      layout: ${{ steps.filter.outputs.layout }}
      layout-core: ${{ steps.filter.outputs['layout-core'] }}
      layout-sakai: ${{ steps.filter.outputs['layout-sakai'] }}
      layout-fuse: ${{ steps.filter.outputs['layout-fuse'] }}
      loader: ${{ steps.filter.outputs.loader }}
      table: ${{ steps.filter.outputs.table }}
      odata: ${{ steps.filter.outputs.odata }}
      form: ${{ steps.filter.outputs.form }}
      tenant: ${{ steps.filter.outputs.tenant }}
      chat: ${{ steps.filter.outputs.chat }}
      socket: ${{ steps.filter.outputs.socket }}
      monaco-field: ${{ steps.filter.outputs['monaco-field'] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          base: 'main'
          filters: |
            core:
              - 'projects/mckit/core/package.json'
            auth:
              - 'projects/mckit/auth/package.json'
            cron:
              - 'projects/mckit/cron/package.json'
            filter:
              - 'projects/mckit/filter/package.json'
            layout:
              - 'projects/mckit/layout/package.json'
            layout-core:
              - 'projects/mckit/layout-core/package.json'
            layout-sakai:
              - 'projects/mckit/layout-sakai/package.json'
            layout-fuse:
              - 'projects/mckit/layout-fuse/package.json'
            loader:
              - 'projects/mckit/loader/package.json'
            table:
              - 'projects/mckit/table/package.json'
            odata:
              - 'projects/mckit/odata/package.json'
            form:
              - 'projects/mckit/form/package.json'
            tenant:
              - 'projects/mckit/tenant/package.json'
            chat:
              - 'projects/mckit/chat/package.json'
            socket:
              - 'projects/mckit/socket/package.json'
            monaco-field:
              - 'projects/mckit/monaco-field/package.json'

  build-and-publish:
    needs: filter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [core, auth, cron, filter, layout, layout-core, layout-sakai, layout-fuse, loader, table, odata, form, tenant, chat, socket, monaco-field]
    steps:
      - name: Checkout repository
        if: ${{ needs.filter.outputs[matrix.project] == 'true' }}
        uses: actions/checkout@v3

      - name: Set up Node.js
        if: ${{ needs.filter.outputs[matrix.project] == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        if: ${{ needs.filter.outputs[matrix.project] == 'true' }}
        run: npm install --force

      - name: Build project
        if: ${{ needs.filter.outputs[matrix.project] == 'true' }}
        run: npm run build-all && npm run build -- --project=@mckit/${{ matrix.project }} --configuration production

      - name: Publish to npm
        if: ${{ needs.filter.outputs[matrix.project] == 'true' }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: dist/mckit/${{ matrix.project }}/package.json
